[enb]
enb_id = 0x19B
mcc = 001
mnc = 01
n_prb = 25
tm = 1
nof_ports = 1
mme_addr = 127.0.1.100
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1

[rf]
device_name = zmq
device_args = tx_port=tcp://*:2000,rx_port=tcp://localhost:2001,id=enb,base_srate=7.68e6
time_adv_nsamples = 0

[log]
all_level = info
phy_level = warning
rf_level = warning
