[enb]
enb_id = 0x19B
mcc = 001
mnc = 01
n_prb = 6
tm = 1
nof_ports = 1
mme_addr = 127.0.1.100
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1

[rf]
device_name = soapy
device_args = driver=bladerf,channel=0,buffers=512,buflen=32768,transfers=64
tx_gain = 70
rx_gain = 40
dl_earfcn = 1950
time_adv_nsamples = 27
srate = 1.92e6

[log]
all_level = info
phy_level = warning
rf_level = warning

[expert]
lte_sample_rates = true
