[enb]
enb_id = 0x19B
mcc = 310
mnc = 260
n_prb = 6
tm = 1
nof_ports = 1
mme_addr = 192.168.1.10
gtp_bind_addr = 192.168.1.20
s1c_bind_addr = 192.168.1.20

[rf]
device_name = soapy
device_args = driver=bladerf
tx_gain = 89
rx_gain = 40
dl_earfcn = 1950
srate = 1.92e6
time_adv_nsamples = 27

[log]
all_level = info
phy_level = warning
rf_level = warning

[expert]
nof_phy_threads = 3
lte_sample_rates = true

[pcap]
enable = true
filename = /tmp/enb_mac.pcap
s1ap_enable = true
s1ap_filename = /tmp/enb_s1ap.pcap
